"""
Scenario YAML loader and arrival-event timeline builder.

A scenario file declares:
  - which nodes to use (preset name or inline list)
  - which algorithms to run
  - how many trials, what seed to base them on
  - when tasks arrive (one or more `arrivals` blocks, each at a time offset)
  - optional `events` (e.g., inject_memory at a specific offset)

This module turns a parsed scenario dict into:
  1. A Scenario object the runner can execute.
  2. For each trial, a sorted list of TimelineEvent objects describing what
     happens at each offset.

Tasks are generated by workload.generator using a seeded RNG so the same
seed produces the same task list — even across separate algorithm runs of
the same trial.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

import yaml

from shared.constants import HETEROGENEOUS_4NODE, get_node_profile
from shared.models import NodeSpec, Task
from shared.task_classes import TaskClass

from workload.generator import generate_batch, parse_mix


# ---------------------------------------------------------------------------
# Scenario representation
# ---------------------------------------------------------------------------


@dataclass
class ArrivalSpec:
    """One entry under `arrivals` in the YAML."""

    at: float                                # offset in seconds from t0
    mix: dict[TaskClass, int]                # per-class counts


@dataclass
class GeneratorArrivalSpec:
    """One `generator:` block under `arrivals` in the YAML."""

    start: float
    interval: float
    count: int
    mix: dict[TaskClass, int]


@dataclass
class EventSpec:
    """One entry under `events` in the YAML.

    type ∈ {"inject_memory", "submit_tasks"}
    """

    at: float
    type: Literal["inject_memory", "submit_tasks"]
    payload: dict                             # type-specific fields


@dataclass
class Scenario:
    """Parsed scenario, ready to feed to the runner."""

    name: str
    description: str = ""
    nodes: list[NodeSpec] = field(default_factory=list)
    algorithms: list[str] = field(default_factory=list)
    trials: int = 1
    seed_base: int = 0
    arrivals: list[ArrivalSpec | GeneratorArrivalSpec] = field(default_factory=list)
    events: list[EventSpec] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Timeline event (what the runner actually executes)
# ---------------------------------------------------------------------------


@dataclass
class TimelineEvent:
    """One thing the runner does at a specific offset."""

    at: float
    kind: Literal["submit_tasks", "inject_memory"]
    # For submit_tasks:
    tasks: list[Task] = field(default_factory=list)
    # For inject_memory:
    node_id: str | None = None
    inject_kb: int = 0
    inject_hold_seconds: float = 0.0


# ---------------------------------------------------------------------------
# YAML loading
# ---------------------------------------------------------------------------


def load_scenario(path: Path | str) -> Scenario:
    """Parse a scenario YAML file into a Scenario object.

    Validates required fields and resolves the `nodes:` reference (either a
    preset name or an inline list of NodeSpec dicts).
    """
    path = Path(path)
    with path.open("r", encoding="utf-8") as f:
        raw = yaml.safe_load(f)
    if not isinstance(raw, dict):
        raise ValueError(f"Scenario {path} did not parse to a dict")
    return _scenario_from_dict(raw, source=str(path))


def _scenario_from_dict(raw: dict, source: str) -> Scenario:
    name = _required(raw, "name", source)
    description = raw.get("description", "")
    nodes = _resolve_nodes(raw.get("nodes"), source)

    algorithms = raw.get("algorithms")
    if not algorithms or not isinstance(algorithms, list):
        raise ValueError(
            f"{source}: 'algorithms' must be a non-empty list"
        )
    trials = int(raw.get("trials", 1))
    if trials < 1:
        raise ValueError(f"{source}: 'trials' must be >= 1")
    seed_base = int(raw.get("seed_base", raw.get("seed", 0)))

    arrivals_raw = raw.get("arrivals", [])
    if not isinstance(arrivals_raw, list):
        raise ValueError(f"{source}: 'arrivals' must be a list")
    arrivals: list[ArrivalSpec | GeneratorArrivalSpec] = []
    for i, entry in enumerate(arrivals_raw):
        arrivals.append(_parse_arrival_entry(entry, f"{source}.arrivals[{i}]"))

    events_raw = raw.get("events", [])
    if not isinstance(events_raw, list):
        raise ValueError(f"{source}: 'events' must be a list")
    events: list[EventSpec] = [
        _parse_event_entry(e, f"{source}.events[{i}]")
        for i, e in enumerate(events_raw)
    ]

    return Scenario(
        name=name,
        description=description,
        nodes=nodes,
        algorithms=list(algorithms),
        trials=trials,
        seed_base=seed_base,
        arrivals=arrivals,
        events=events,
    )


def _required(d: dict, key: str, source: str):
    if key not in d:
        raise ValueError(f"{source}: missing required field '{key}'")
    return d[key]


def _resolve_nodes(value, source: str) -> list[NodeSpec]:
    """nodes: can be either a preset name (string) or an inline list."""
    if value is None:
        # Default: heterogeneous 4-node configuration.
        return list(HETEROGENEOUS_4NODE)
    if isinstance(value, str):
        return get_node_profile(value)
    if isinstance(value, list):
        out: list[NodeSpec] = []
        for i, entry in enumerate(value):
            if not isinstance(entry, dict):
                raise ValueError(
                    f"{source}.nodes[{i}] must be a dict (NodeSpec fields)"
                )
            out.append(NodeSpec(**entry))
        return out
    raise ValueError(
        f"{source}: 'nodes' must be a preset name (string) or inline list"
    )


def _parse_arrival_entry(entry: dict, source: str):
    if not isinstance(entry, dict):
        raise ValueError(f"{source} must be a dict")
    if "generator" in entry:
        g = entry["generator"]
        return GeneratorArrivalSpec(
            start=float(_required(g, "start", source + ".generator")),
            interval=float(_required(g, "interval", source + ".generator")),
            count=int(_required(g, "count", source + ".generator")),
            mix=parse_mix(_required(g, "mix", source + ".generator")),
        )
    return ArrivalSpec(
        at=float(_required(entry, "at", source)),
        mix=parse_mix(_required(entry, "tasks", source)),
    )


def _parse_event_entry(entry: dict, source: str) -> EventSpec:
    at = float(_required(entry, "at", source))
    etype = _required(entry, "type", source)
    if etype == "inject_memory":
        return EventSpec(
            at=at,
            type="inject_memory",
            payload={
                "node_id": _required(entry, "node_id", source),
                "kb": int(_required(entry, "kb", source)),
                "hold_seconds": float(_required(entry, "hold_seconds", source)),
            },
        )
    if etype == "submit_tasks":
        return EventSpec(
            at=at,
            type="submit_tasks",
            payload={"mix": parse_mix(_required(entry, "tasks", source))},
        )
    raise ValueError(
        f"{source}: unknown event type '{etype}'. "
        f"Valid types: inject_memory, submit_tasks"
    )


# ---------------------------------------------------------------------------
# Timeline construction
# ---------------------------------------------------------------------------


def build_task_timeline(
    scenario: Scenario,
    seed: int,
    id_prefix: str,
) -> list[TimelineEvent]:
    """Generate the deterministic event timeline for one trial.

    The same seed produces the same tasks every time, regardless of which
    algorithm will later run against them. The runner calls this once per
    trial, then replays the resulting list once per algorithm.
    """
    rng = random.Random(seed)
    events: list[TimelineEvent] = []
    seq = 0

    # Process arrivals.
    for spec in scenario.arrivals:
        if isinstance(spec, ArrivalSpec):
            tasks, seq = generate_batch(
                rng=rng,
                mix=spec.mix,
                id_prefix=id_prefix,
                next_seq=seq,
                arrival_offset=spec.at,
            )
            if tasks:
                events.append(
                    TimelineEvent(at=spec.at, kind="submit_tasks", tasks=tasks)
                )
        else:  # GeneratorArrivalSpec
            # Distribute the mix across `count` arrivals at fixed intervals.
            # The mix is interpreted as the TOTAL across all `count` arrivals,
            # apportioned round-robin so the count-per-arrival is balanced.
            apportioned = _apportion_mix_round_robin(spec.mix, spec.count)
            for i in range(spec.count):
                arrival_at = spec.start + i * spec.interval
                slot_mix = apportioned[i]
                tasks, seq = generate_batch(
                    rng=rng,
                    mix=slot_mix,
                    id_prefix=id_prefix,
                    next_seq=seq,
                    arrival_offset=arrival_at,
                )
                if tasks:
                    events.append(
                        TimelineEvent(
                            at=arrival_at,
                            kind="submit_tasks",
                            tasks=tasks,
                        )
                    )

    # Process explicit events (inject_memory, submit_tasks).
    for ev in scenario.events:
        if ev.type == "inject_memory":
            events.append(
                TimelineEvent(
                    at=ev.at,
                    kind="inject_memory",
                    node_id=ev.payload["node_id"],
                    inject_kb=ev.payload["kb"],
                    inject_hold_seconds=ev.payload["hold_seconds"],
                )
            )
        elif ev.type == "submit_tasks":
            tasks, seq = generate_batch(
                rng=rng,
                mix=ev.payload["mix"],
                id_prefix=id_prefix,
                next_seq=seq,
                arrival_offset=ev.at,
            )
            if tasks:
                events.append(
                    TimelineEvent(at=ev.at, kind="submit_tasks", tasks=tasks)
                )

    # Stable sort by time. Python's sort is stable, so events at the same
    # offset retain their declaration order.
    events.sort(key=lambda e: e.at)
    return events


def _apportion_mix_round_robin(
    mix: dict[TaskClass, int], slots: int
) -> list[dict[TaskClass, int]]:
    """Spread a class-count mix across `slots` arrivals as evenly as
    possible. For mix={lightweight: 5} and slots=3 → [{l:2}, {l:2}, {l:1}].
    Per-class apportionment is independent so e.g. lightweight totals can
    differ in distribution from heavy totals."""
    if slots <= 0:
        return []
    apportioned: list[dict[TaskClass, int]] = [
        {} for _ in range(slots)
    ]
    for cls, total in mix.items():
        if total <= 0:
            continue
        base, extra = divmod(total, slots)
        for i in range(slots):
            count = base + (1 if i < extra else 0)
            if count > 0:
                apportioned[i][cls] = count
    return apportioned